### ISSUE TITLE
ERROR:CHANGE GO1 

### ISSUE THREAD

**Issue by hhzhsg** [Alescontrela/AMP_for_hardware#13]
**Describe the bug**
It seems like when I replace the robot with 'go1', the limbs become detached from the body. Additionally, in the final learned behavior of 'go1', the front legs move, but the hind legs only spread apart to the sides without any movement. Have you encountered such an issue before, and how should it be resolved?

**To Reproduce**
![20231213-214306](https://github.com/Alescontrela/AMP_for_hardware/assets/59784307/3e1be8ba-73e0-406a-a5bf-2aaf96850436)

**Expected behavior**

**System (please complete the following information):**
 - Commit: [e.g. 8f3b9ca]
 - OS: [e.g. Ubuntu 20.04]
 - GPU: [e.g. RTX 4070TI]
 - CUDA: [e.g. 12.3]
 - GPU Driver: [e.g. 535]

**Additional context**

**Comment by Alescontrela** [comment]
I'm not really sure, this repo wasn't designed for the Go1. Maybe play with this setting:

https://github.com/Alescontrela/AMP_for_hardware/blob/799ded43ed6fca725344f28eefc0fb97cb932e53/legged_gym/envs/base/legged_robot_config.py#L111C1-L112C1

It might just be a visual thing. Closing for now
