### ISSUE TITLE
No trained file 

### ISSUE THREAD

**Issue by JeffXu1** [Alescontrela/AMP_for_hardware#3]
**Describe the bug**
There is no logs file.

**To Reproduce**
1. Execute `python legged_gym/scripts/play.py --task=a1_amp`
1. Then report no logs run file
I assume that you didn't put the saved agent policy model file which you used in the code file, could you release it?
And could you give a guide how to implement the code in Unitree A1? I will appreciate it very much!
.

**Comment by Alescontrela** [comment]
Hi Jeff. Thanks for pointing this out. I just uploaded a trained checkpoint to the repo. You should be able to run it with:

```
python legged_gym/scripts/play.py --task=a1_amp
```

Closing for now, feel free to re-open if you run into any issues.
