### ISSUE TITLE
Race Data

### ISSUE THREAD

**Issue by JeffXu1** [Alescontrela/AMP_for_hardware#4]
**Describe the bug**
I check the website https://sites.google.com/berkeley.edu/amp-in-real/home experiment result, from the result "Informal race between Fu et al.* (left) and AMP Policy (right)", we could see A1 could run at a very high speed, but I check the trot0 and trot1 data from datasets file, it seems these data are not related to race, if yes, could you provide motion data related to race experiment? Thanks!

**To Reproduce**
1. Execute `./path/script arg1 arg2`
1. Then ... 
1. See error: ...

**Expected behavior**

**System (please complete the following information):**
 - Commit: [e.g. 8f3b9ca]
 - OS: [e.g. Ubuntu 20.04]
 - GPU: [e.g. RTX 2060 Super]
 - CUDA: [e.g. 11.4]
 - GPU Driver: [e.g. 470.82.01]

**Additional context**

**Comment by Alescontrela** [comment]
I added the canter reference data used in the race, as well as the motion re-targeting scripts to this branch: https://github.com/Alescontrela/AMP_for_hardware/tree/retarget_scripts
