### ISSUE TITLE
Low speed for training

### ISSUE THREAD

**Issue by Joe618** [Alescontrela/AMP_for_hardware#5]
**Describe the bug**
Hi, the problem I meet now is the low speed for training. I remember you presented a result that the training was finished in 20 minutes, while executing the program by myself costed about 9-10 days. Do you know what happened with it? And what were commands you used in the terminal when you operated the program？

**To Reproduce**
1.  cd AMP_for_hardware/
2. Then use ‘’’python legged_gym/scripts/train.py —task=a1_amp —headless —num_envs=1000 ‘’’
3. The terminal shows Iteration time is about 1.76s, ETA is about 760000s

**Expected behavior**
I hope I can reproduce your result that spending about 20minutes finishes the train. Do you know what happened with it that the training speed is too slow? And what were commands you input to the terminal when you operated the program？

**System (please complete the following information):**
 - OS: Centos7
 - GPU: Intel A100(80G), Note: the usage is 37% when I operate the train.py
 - CUDA: 11.3
 - GPU Driver: 510.47.03

**Comment by Alescontrela** [comment]
Hi, I'm not really sure. I'm not really sure if PyTorch is compatible with Intel GPUs (did I read that right?). If you find a fix please let me know and I will merge!
