### ISSUE TITLE
Question about motion data.

### ISSUE THREAD

**Issue by jonyzhang2023** [Alescontrela/AMP_for_hardware#6]
Hi Alescontrela,
    Thanks for your great job on amp_for_hardware!
    I can train it on a1, it is awesome. I have a question that I find that your mocap data is txt file and issacgym offical data, ase/amp mocap data is npy file. I want to try humanoid motion data on your repo. could you tell me how to translate that data?
    I noticed that your code AMP_LOADER has 'reorder_from_pybullet_to_isaac', is that translated by pybullet?
    Thanks!

**Comment by zituka** [comment]
@Alescontrela
