### ISSUE TITLE
What's the hopturn task config setting?

### ISSUE THREAD

**Issue by yangyichu** [Alescontrela/AMP_for_hardware#7]
Hi @Alescontrela  I'm trying to reproduce the hopturn result using the provided hopturn dataset, I'm wondering what's your training setting for the hopturn task, if possible can you share the config used for the hopturn task?

**Comment by terry97-guel** [comment]
Hello @Alescontrela. I am having same issue here.

I have tried eliminating task reward term leaving only the style reward (i.e. motion priors), but if did not work.
I would fully appreciate if you can share us configurations for hopturn task or any other source code to reproduce your work .

Thanks in advance.

**Comment by Alescontrela** [comment]
If I remember currently, I used the same config for all experiments: https://github.com/Alescontrela/AMP_for_hardware/blob/retarget_scripts/legged_gym/envs/a1/a1_amp_config.py

and the following dataset for the hopturn task:
https://github.com/Alescontrela/AMP_for_hardware/tree/retarget_scripts/datasets/hopturn

I think this branch might lead to better results. Let me know if it works! closing for now
