### ISSUE TITLE
more mocap motions data

### ISSUE THREAD

**Issue by COST-97** [Alescontrela/AMP_for_hardware#8]
Hello:
    Your work is interesting! 
     How to obtain more motions data (A1 robot)?
     The file "dog_clips_info.txt" included many task names, but  the file "mocap_motions_a1/" only included several tasks.

**Comment by lgd21356** [comment]
Maybe this one will be helpful.
https://github.com/inspirai/MetalHead

**Comment by Alescontrela** [comment]
This branch contains more mocap motions:
https://github.com/Alescontrela/AMP_for_hardware/tree/retarget_scripts/datasets
